### ISSUE TITLE
Incorrect property name case of YAML serialized results

### ISSUE THREAD

**Issue by BernieWhite** [BernieWhite/PSRule#114]
**Description of the issue**

Results for `Invoke-PSRule` with `-OutputFormat Yaml` should produce results formatted with lower camel case property names.

**To Reproduce**

Steps to reproduce the issue:

```powershell
Get-Content docs/scenarios/kubernetes-resources/resources.yaml -Raw | Invoke-PSRule -Path docs/scenarios/kubernetes-resources -Format Yaml -Option docs/scenarios/kubernetes-resources/PSRule.yaml -Outcome Fail -OutputFormat Yaml
```

```yaml
- RuleId: kubernetes.Rule.ps1/deployment.HasMinimumReplicas
  RuleName: deployment.HasMinimumReplicas
- RuleId: kubernetes.Rule.ps1/deployment.NotLatestImage
  RuleName: deployment.NotLatestImage
- RuleId: kubernetes.Rule.ps1/deployment.ResourcesSet
  RuleName: deployment.ResourcesSet
- RuleId: kubernetes.Rule.ps1/metadata.Name
  RuleName: metadata.Name
- RuleId: kubernetes.Rule.ps1/metadata.Version
  RuleName: metadata.Version
- RuleId: kubernetes.Rule.ps1/metadata.Component
  RuleName: metadata.Component
- RuleId: kubernetes.Rule.ps1/metadata.Version
  RuleName: metadata.Version
```

**Expected behaviour**

Serialized YAML results should use lower camel casing for property names.

**Module in use and version:**

- Module: PSRule
- Version: **0.4.0-B190320**

Captured output from `$PSVersionTable`:

```text
Name                           Value
----                           -----
PSVersion                      5.1.17763.316
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17763.316
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```
