### ISSUE TITLE
Suppress objects from being reported

### ISSUE THREAD

**Issue by BernieWhite** [BernieWhite/PSRule#13]
In certain circumstances it may be necessary to exclude or suppress rules from processing objects that are in a known failed state.

Consider:

```yaml
suppression:
  storageAccounts.UseHttps:
    targetName:
      - storage
```

```yaml
suppression:
  storageAccounts.UseHttps: storage
```
