### ISSUE TITLE
Support named baselines

### ISSUE THREAD

**Issue by BernieWhite** [BernieWhite/PSRule#274]
Currently a baseline configuration can be included in PSRule options within a `ps-rule.yaml` file.

For example:

```yaml
# Configure baseline
baseline:
  ruleName:
  - rule1
  - rule2
  exclude:
  - rule3
  - rule4
  configuration:
    appServiceMinInstanceCount: 2
```

While this works for configuration within a workspace, it is not possible to ship these options within a module.

Additionally a module may want to provide more then one baseline. For example a full baseline or a security baseline.

Also it is highly likely that different types of objects will be processed by modules. Consider an Azure resource vs a Kubernetes resource.

For Azure: `TargetName = "ResourceName"`; `TargetType = "ResourceType"`
For Kubernetes: `TargetName = "metadata.name"`; `TargetType = "kind"`

Requiring something like the following to be configure to work with different resource types.

```yaml
# Configure binding
binding:
  ignoreCase: false
  targetName:
  - ResourceName
  - metadata.name
  targetType:
  - ResourceType
  - kind
```

Including binding options within a baseline would minimize the the requirement to add options in the local workspace for module defaults.

- [x] Allow separate named baselines to be created
- [x] Allow modules to include baselines
- [x] Allow modules to specify a default baseline
- [x] Restructure baseline and baseline configuration options to provide consistency

Related to #210
