### ISSUE TITLE
Support TargetName binding of nested properties

### ISSUE THREAD

**Issue by BernieWhite** [BernieWhite/PSRule#71]
When an object is passed from the pipeline, PSRule assigns the object a _TargetName_. _TargetName_ is used in output results to identify one object from another.

Currently direct properties of the pipeline object can be bound, or a custom script block can be used to perform binding.

Using a custom script block is highly flexible but has performance impacts. For simple cases like nested properties, it would be better to provide this feature natively.

A similar feature was added in #60 for `Exists`, `Within` and `Match` keywords.

For example:

```yaml
# Use the metadata.name property as TargetName
binding:
  targetName:
  - 'metadata.name'
```

An example Kubernetes namespace object:

```yaml
---
# Namespace: dev
apiVersion: v1
kind: Namespace
metadata:
  name: dev
```

Using `metadata.name` to bind _TargetName_ should return `dev`.
