### ISSUE TITLE
Add object type binding and dynamic filtering for rules

### ISSUE THREAD

**Issue by BernieWhite** [BernieWhite/PSRule#82]
Currently rules can be dynamically filtered at runtime by using a preconditions to select rules that apply to a certain objects. Preconditions are defined as PowerShell script blocks using the `-If` parameter on a `Rule` definition.

In many cases preconditions filter based on the type of object.

Providing an option to dynamically filter rules based on a bound type would reduce some complexity and improve performance because binding can be done up front for all rules.

Example rule:

```powershell
Rule 'typeFiltedRule' -Type 'Microsoft.Storage/storageAccounts' {
    # Rule body
}
```

Example binding option:

```yaml
# Bind to the ResourceType property of the object to determine TargetType
binding:
  targetType:
  - ResourceType
```

Instead of:

```powershell
Rule 'typeFiltedRule' -If { $TargetObject.ResourceType -eq 'Microsoft.Storage/storageAccounts' } {
    # Rule body
}
```
